alter table "public"."organisation" drop constraint "organisation_name_key";

drop index if exists "public"."organisation_name_key";

create table "public"."global_system_settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "register_enabled" boolean not null default true,
    "populate_apikeys" boolean not null default true,
    "populate_organisation" boolean not null default true,
    "user_can_create_organisation" boolean not null default true,
    "organisation_limit" integer not null default 3
);


alter table "public"."global_system_settings" enable row level security;

CREATE UNIQUE INDEX global_system_settings_pkey ON public.global_system_settings USING btree (id);

alter table "public"."global_system_settings" add constraint "global_system_settings_pkey" PRIMARY KEY using index "global_system_settings_pkey";

grant delete on table "public"."global_system_settings" to "anon";

grant insert on table "public"."global_system_settings" to "anon";

grant references on table "public"."global_system_settings" to "anon";

grant select on table "public"."global_system_settings" to "anon";

grant trigger on table "public"."global_system_settings" to "anon";

grant truncate on table "public"."global_system_settings" to "anon";

grant update on table "public"."global_system_settings" to "anon";

grant delete on table "public"."global_system_settings" to "authenticated";

grant insert on table "public"."global_system_settings" to "authenticated";

grant references on table "public"."global_system_settings" to "authenticated";

grant select on table "public"."global_system_settings" to "authenticated";

grant trigger on table "public"."global_system_settings" to "authenticated";

grant truncate on table "public"."global_system_settings" to "authenticated";

grant update on table "public"."global_system_settings" to "authenticated";

grant delete on table "public"."global_system_settings" to "service_role";

grant insert on table "public"."global_system_settings" to "service_role";

grant references on table "public"."global_system_settings" to "service_role";

grant select on table "public"."global_system_settings" to "service_role";

grant trigger on table "public"."global_system_settings" to "service_role";

grant truncate on table "public"."global_system_settings" to "service_role";

grant update on table "public"."global_system_settings" to "service_role";


