create table "public"."paddle_customer_products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "customer_id" text not null,
    "product_id" text not null,
    "by_price_id" text not null
);


alter table "public"."paddle_customer_products" enable row level security;

create table "public"."paddle_customer_subscriptions" (
    "created_at" timestamp with time zone not null default now(),
    "subscription_id" text not null,
    "subscription_status" text not null,
    "price_id" text,
    "product_id" text,
    "scheduled_change" text,
    "customer_id" text not null,
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."paddle_customer_subscriptions" enable row level security;

create table "public"."paddle_customers" (
    "customer_id" text not null,
    "email" text not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default now(),
    "marketing_consent" boolean not null default false
);


alter table "public"."paddle_customers" enable row level security;

create table "public"."paddle_events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "item" jsonb not null,
    "type" text not null
);


alter table "public"."paddle_events" enable row level security;

CREATE UNIQUE INDEX paddle_customer_products_pkey ON public.paddle_customer_products USING btree (id);

CREATE UNIQUE INDEX paddle_customer_subscriptions_pkey ON public.paddle_customer_subscriptions USING btree (subscription_id);

CREATE UNIQUE INDEX paddle_customers_pkey ON public.paddle_customers USING btree (customer_id);

CREATE UNIQUE INDEX paddle_events_pkey ON public.paddle_events USING btree (id);

alter table "public"."paddle_customer_products" add constraint "paddle_customer_products_pkey" PRIMARY KEY using index "paddle_customer_products_pkey";

alter table "public"."paddle_customer_subscriptions" add constraint "paddle_customer_subscriptions_pkey" PRIMARY KEY using index "paddle_customer_subscriptions_pkey";

alter table "public"."paddle_customers" add constraint "paddle_customers_pkey" PRIMARY KEY using index "paddle_customers_pkey";

alter table "public"."paddle_events" add constraint "paddle_events_pkey" PRIMARY KEY using index "paddle_events_pkey";

alter table "public"."paddle_customer_products" add constraint "paddle_customer_products_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES paddle_customers(customer_id) not valid;

alter table "public"."paddle_customer_products" validate constraint "paddle_customer_products_customer_id_fkey";

alter table "public"."paddle_customer_subscriptions" add constraint "paddle_customer_subscriptions_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES paddle_customers(customer_id) not valid;

alter table "public"."paddle_customer_subscriptions" validate constraint "paddle_customer_subscriptions_customer_id_fkey";

grant delete on table "public"."paddle_customer_products" to "anon";

grant insert on table "public"."paddle_customer_products" to "anon";

grant references on table "public"."paddle_customer_products" to "anon";

grant select on table "public"."paddle_customer_products" to "anon";

grant trigger on table "public"."paddle_customer_products" to "anon";

grant truncate on table "public"."paddle_customer_products" to "anon";

grant update on table "public"."paddle_customer_products" to "anon";

grant delete on table "public"."paddle_customer_products" to "authenticated";

grant insert on table "public"."paddle_customer_products" to "authenticated";

grant references on table "public"."paddle_customer_products" to "authenticated";

grant select on table "public"."paddle_customer_products" to "authenticated";

grant trigger on table "public"."paddle_customer_products" to "authenticated";

grant truncate on table "public"."paddle_customer_products" to "authenticated";

grant update on table "public"."paddle_customer_products" to "authenticated";

grant delete on table "public"."paddle_customer_products" to "service_role";

grant insert on table "public"."paddle_customer_products" to "service_role";

grant references on table "public"."paddle_customer_products" to "service_role";

grant select on table "public"."paddle_customer_products" to "service_role";

grant trigger on table "public"."paddle_customer_products" to "service_role";

grant truncate on table "public"."paddle_customer_products" to "service_role";

grant update on table "public"."paddle_customer_products" to "service_role";

grant delete on table "public"."paddle_customer_subscriptions" to "anon";

grant insert on table "public"."paddle_customer_subscriptions" to "anon";

grant references on table "public"."paddle_customer_subscriptions" to "anon";

grant select on table "public"."paddle_customer_subscriptions" to "anon";

grant trigger on table "public"."paddle_customer_subscriptions" to "anon";

grant truncate on table "public"."paddle_customer_subscriptions" to "anon";

grant update on table "public"."paddle_customer_subscriptions" to "anon";

grant delete on table "public"."paddle_customer_subscriptions" to "authenticated";

grant insert on table "public"."paddle_customer_subscriptions" to "authenticated";

grant references on table "public"."paddle_customer_subscriptions" to "authenticated";

grant select on table "public"."paddle_customer_subscriptions" to "authenticated";

grant trigger on table "public"."paddle_customer_subscriptions" to "authenticated";

grant truncate on table "public"."paddle_customer_subscriptions" to "authenticated";

grant update on table "public"."paddle_customer_subscriptions" to "authenticated";

grant delete on table "public"."paddle_customer_subscriptions" to "service_role";

grant insert on table "public"."paddle_customer_subscriptions" to "service_role";

grant references on table "public"."paddle_customer_subscriptions" to "service_role";

grant select on table "public"."paddle_customer_subscriptions" to "service_role";

grant trigger on table "public"."paddle_customer_subscriptions" to "service_role";

grant truncate on table "public"."paddle_customer_subscriptions" to "service_role";

grant update on table "public"."paddle_customer_subscriptions" to "service_role";

grant delete on table "public"."paddle_customers" to "anon";

grant insert on table "public"."paddle_customers" to "anon";

grant references on table "public"."paddle_customers" to "anon";

grant select on table "public"."paddle_customers" to "anon";

grant trigger on table "public"."paddle_customers" to "anon";

grant truncate on table "public"."paddle_customers" to "anon";

grant update on table "public"."paddle_customers" to "anon";

grant delete on table "public"."paddle_customers" to "authenticated";

grant insert on table "public"."paddle_customers" to "authenticated";

grant references on table "public"."paddle_customers" to "authenticated";

grant select on table "public"."paddle_customers" to "authenticated";

grant trigger on table "public"."paddle_customers" to "authenticated";

grant truncate on table "public"."paddle_customers" to "authenticated";

grant update on table "public"."paddle_customers" to "authenticated";

grant delete on table "public"."paddle_customers" to "service_role";

grant insert on table "public"."paddle_customers" to "service_role";

grant references on table "public"."paddle_customers" to "service_role";

grant select on table "public"."paddle_customers" to "service_role";

grant trigger on table "public"."paddle_customers" to "service_role";

grant truncate on table "public"."paddle_customers" to "service_role";

grant update on table "public"."paddle_customers" to "service_role";

grant delete on table "public"."paddle_events" to "anon";

grant insert on table "public"."paddle_events" to "anon";

grant references on table "public"."paddle_events" to "anon";

grant select on table "public"."paddle_events" to "anon";

grant trigger on table "public"."paddle_events" to "anon";

grant truncate on table "public"."paddle_events" to "anon";

grant update on table "public"."paddle_events" to "anon";

grant delete on table "public"."paddle_events" to "authenticated";

grant insert on table "public"."paddle_events" to "authenticated";

grant references on table "public"."paddle_events" to "authenticated";

grant select on table "public"."paddle_events" to "authenticated";

grant trigger on table "public"."paddle_events" to "authenticated";

grant truncate on table "public"."paddle_events" to "authenticated";

grant update on table "public"."paddle_events" to "authenticated";

grant delete on table "public"."paddle_events" to "service_role";

grant insert on table "public"."paddle_events" to "service_role";

grant references on table "public"."paddle_events" to "service_role";

grant select on table "public"."paddle_events" to "service_role";

grant trigger on table "public"."paddle_events" to "service_role";

grant truncate on table "public"."paddle_events" to "service_role";

grant update on table "public"."paddle_events" to "service_role";


