create table "public"."paddle_product_tier" (
    "id" bigint generated by default as identity not null,
    "product_id" text not null,
    "tier_level" smallint not null
);


alter table "public"."paddle_product_tier" enable row level security;

CREATE UNIQUE INDEX paddle_product_tier_pkey ON public.paddle_product_tier USING btree (id);

CREATE UNIQUE INDEX paddle_product_tier_product_id_key ON public.paddle_product_tier USING btree (product_id);

alter table "public"."paddle_product_tier" add constraint "paddle_product_tier_pkey" PRIMARY KEY using index "paddle_product_tier_pkey";

alter table "public"."paddle_product_tier" add constraint "paddle_product_tier_product_id_key" UNIQUE using index "paddle_product_tier_product_id_key";

grant delete on table "public"."paddle_product_tier" to "anon";

grant insert on table "public"."paddle_product_tier" to "anon";

grant references on table "public"."paddle_product_tier" to "anon";

grant select on table "public"."paddle_product_tier" to "anon";

grant trigger on table "public"."paddle_product_tier" to "anon";

grant truncate on table "public"."paddle_product_tier" to "anon";

grant update on table "public"."paddle_product_tier" to "anon";

grant delete on table "public"."paddle_product_tier" to "authenticated";

grant insert on table "public"."paddle_product_tier" to "authenticated";

grant references on table "public"."paddle_product_tier" to "authenticated";

grant select on table "public"."paddle_product_tier" to "authenticated";

grant trigger on table "public"."paddle_product_tier" to "authenticated";

grant truncate on table "public"."paddle_product_tier" to "authenticated";

grant update on table "public"."paddle_product_tier" to "authenticated";

grant delete on table "public"."paddle_product_tier" to "service_role";

grant insert on table "public"."paddle_product_tier" to "service_role";

grant references on table "public"."paddle_product_tier" to "service_role";

grant select on table "public"."paddle_product_tier" to "service_role";

grant trigger on table "public"."paddle_product_tier" to "service_role";

grant truncate on table "public"."paddle_product_tier" to "service_role";

grant update on table "public"."paddle_product_tier" to "service_role";


